/*******************************************************************
* @Class Name      : ARBConstantValues
* @Author          : RAGESH G
* @Created Date    : 20 January 2021
* @description 	   : This class is used to write all the constant values accross the application
* @JIRA            : SFD-271

  LOG   DATE        Author  UserStory       	COMMENT      
* 001   10/01/2021  RG                       First Commit
********************************************************************/
public with sharing class ARBConstantValues {
    
    public static String CASE_PRIORITY = System.Label.ARB_Case_Priority;
    public static String CASE_STATUS = System.Label.ARB_Case_Status;
    public static String CASE_ORIGIN = System.Label.ARB_Case_Origin;

    public static String CASE_RECORD_TYPE = System.Label.ARB_Case_Record_Type;
}