/* ----------------------------------------------------------------------------	*/
/* C0633																		*/
/* ----------------------------------------------------------------------------	*/


public class DeleteCustomerResponse 
{ 
	public string msgID {get ; set ;}
	public string EBSID {get ; set ;}	
	public string SFDCID {get ; set ;}
	public string PanopticID {get ; set ;}
	public string responseCode {get ; set ;}
	public string responseMessage {get ; set;}
}