/* ---------------------------------------------------------------------------------------- */
/* C0530                                                                                    */
/* ---------------------------------------------------------------------------------------- */

public without sharing class DocumentManagementCaseResponse
{
    public String MessageID;
    public String DocumentUDI;
    public String ResponseCode;
    public String ResponseMsg;
    public DocumentManagementCaseResponse()
    {}
}