public class DocumentManagementCase
{
    public string MessageID {get;set;}
    public string MessageType {get;set;}
    public string ReplicationType {get;set;}
    public string CustNo {get;set;}
    public string CaseDirectorCode {get;set;}
    public string CaseDescription {get;set;}
    public string CaseSubject {get;set;}
    public string CaseUser {get;set;}
    public string CasePriority {get;set;}
    public string CaseStatus {get;set;}
    public string CaseQueue {get;set;}
    public string DocumentDefinitionName {get;set;}
    public string DocumentName {get;set;}
    public string DocumentUDI {get;set;}
    public string ProcessStatus  {get;set;}
    public string CustomerNumber {get;set;}
    public string AccountNumber {get;set;}
    public string Branch {get;set;}
    public string FirstName {get;set;}
    public string LastName {get;set;}
    public string PostCode {get;set;}
    public string DocumentReference {get;set;}
    public string CompletionDate {get;set;}
    public string DocumentDate {get;set;}
    public string DocumentTime {get;set;}
    public string ActionStatus  {get;set;}
    public string WorkLocation  {get;set;}
    public DocumentManagementCase()
    {}
}