/* ---------------------------------------------------------------------------------------------------	*/
/* C0689 Process HR SML requests web service															*/
/* ---------------------------------------------------------------------------------------------------	*/


public class HRSMLResponse 
{ 
	public string JobID {get ; set ;}
	public string ResponseCode {get ; set ;}
	public string ResponseMessage {get ; set ; }
}