/* ---------------------------------------------------------------------------------------------------	*/
/* C0689 Process HR SML requests web service															*/
/* ---------------------------------------------------------------------------------------------------	*/


public class HRSMLRequestRecord
{ 
	public string EmployeeId {get; set ;}
	public string Title {get; set ;}
	public string FirstName {get; set ;}
	public string LastName {get; set ;}
	public string KnownAs {get; set ;}
	public string WorkEmail {get; set ;}
	public string StartDate {get; set ;}
	public string JobRole {get; set ;}
	public string Location {get; set ;}
	public string Department {get; set ;}
	public string ReportsTo {get; set ;}
	public string EmploymentType {get; set ;}
	public string FinalDayofEmployment {get; set ;}
	public string FinalDayinOffice {get; set ;}
	public string EffectiveFrom {get; set ;}
	
}