/* -------------------------------------------------------------------------------------- */
/* C0Steve	New classes for International Payments - Steve F to update reference		  */
/* -------------------------------------------------------------------------------------- */

public class InternationalPaymentResponse 
{ 
	public integer IFMID {get; Set;}
	public string MessageID {get;Set;}
	public string MessageType {get;Set;}
	public string ResponseCode {get; Set;}
	public string ResponseMessage {get;Set;}
}