global class TransactionHistoryItem {

        public string itemPostingDate {get; set;} 
        public string itemValueDate {get; set;}          
        public string itemTranName {get; set;}
        public string itemRef {get; set;}
        public string itemDesc {get; set;}        
        public Decimal itemDebit {get; set;}     
        public Decimal itemCredit {get; set;}     
        public string itemPosted {get; set;}
        public Decimal itemRunningBalance {get; set;}
        public string itemDisplayDebit {get; set;}
        public string itemDisplayCredit {get; set;}
        public string itemDisplayRunningBalance {get; set;} 
        public integer itemDisplayOrder {get; set;}       
 
        
    }