/* ---------------------------------------------------------------------------------------- */
/* C0550 endpoint for UpdateFTDOpportunity                                                  */
/* ---------------------------------------------------------------------------------------- */

public without sharing class UpdateFTDOpportunityResponse
{
    public String MessageID;
    
    public String ResponseCode;
    public String ResponseMsg;
    public UpdateFTDOpportunityResponse()
    {}
}